{
    "application": False,
    "author": "Marc Wimmer (marc@zebroo.de)",
    'css': [   'static/css/diagrams_net.scss',
               'static/lib/vis/vis-network.min.css'],
    "data": ["views/assets.xml"],
    "demo": [],
    "depends": ["web"],
    "external_dependencies": {"bin": [], "python": []},
    "name": "diagrams_net",
    "test": [],
    "version": "1.0",
    "web": True,
    "qweb": ["static/src/diagrams_net.xml"],
}
