{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'css': [   'static/css/diagrams_net.scss',
               'static/lib/vis/vis-network.min.css'],
    'data': ['views/assets.xml'],
    'demo': [],
    'depends': ['web'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'diagrams_net',
    'qweb': ['static/xml/diagrams_net.xml'],
    'test': [],
    'version': '1.0',
    'web': True}
