# .github/workflows/flow1.yml
name: Deploy fixes to other versions with rebase main

on:
  push:
    branches:
      - 14.0

permissions: write-all

jobs:
  deploy-subversions:
    uses: Odoo-Ninjas/git-workflows/.github/workflows/deploy_to_subversions.yml@v10
    with:
      branches: 13.0:14.0
      runner_label: self-hosted
    secrets:
      SSH_PRIVATE_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}